version: "3.9"
services:
  api:
    image: myapi:latest
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
      mailing:
        condition: service_started

  db:
    image: postgres:16.3-alpine
    

  cache: 
    image: redis:7.2.5-alpine
    container_name: redis_cache
    hostname: cache
    ports:
      - "6379:6379"

  mailing:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  django:
    build: .
    
    depends_on:
      - db
      - cache 

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker -l info
    env_file:
      - .env
    depends_on:
      - cache
      - db
    volumes:
      - .:/app
      
  celery_high:
    build: .
    command: celery -A config worker -l info -Q high_priority -c 2
    depends_on:
      - django
      - cache
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://cache:6379/1}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-redis://cache:6379/2}

  celery_low:
    build: .
    command: celery -A config worker -l info -Q low_priority -c 2
    depends_on:
      - django
      - cache
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://cache:6379/1}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-redis://cache:6379/2}

  flower:
    build: .
    command: celery -A config flower --broker=${CELERY_BROKER_URL:-redis://cache:6379/1}
    ports:
      - "5555:5555"
    depends_on:
      - django
      - cache

  silpo-mock:
    build:
      context: .
      dockerfile: Dockerfile.test
      target: silpo
    container_name: catering-silpo-mock
    ports:
      - "8001:8000"
  kfc-mock:
    build:
      context: .
      dockerfile: Dockerfile.test
      target: kfc
    container_name: catering-kfc-mock
    ports:
      - "8002:8000"
  uklon-mock:
    build:
      context: .
      dockerfile: Dockerfile.test
      target: uklon
    container_name: catering-uklon-mock
    ports:
      - "8003:8000"

volumes:
  db_data:
