[tool.black]
line-length = 120
target-version = ['py312']
exclude = '''
/(\.
    | \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | archive
    | docs
  )/
)
...


[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
skip = ["archive", "docs"]


[tool.mypy]
plugins = [
    "mypy_django_plugin.main",
    "mypy_drf_plugin.main",
]
python_version = 3.12
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true
namespace_packages = true
pretty = true
exclude = []
follow_imports = "silent"
ignore_missing_imports = true

[tool.mypy_django_stubs]
django_settings_module = "config.settings"